global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc.Rendering;
global using System.ComponentModel.DataAnnotations;
global using Tiers.BLL.Responses;
global using AutoMapper;
global using Tiers.BLL.Helper;
global using Microsoft.Extensions.DependencyInjection;
global using Tiers.BLL.AutoMapper;
global using Tiers.BLL.Service.Abstraction;